#!/usr/bin/env bash
#
# author: daniel neemann (@zzzeyez)
#
# requires Übersicht
# optional dependency: `imagemagick` (to save screenshots when saving theme)

name="$2"

setup() {
	SOURCE="${BASH_SOURCE[0]}"
	while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
		DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
		SOURCE="$(readlink "$SOURCE")"
		[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
	done
	pecan="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
	themes="$pecan/themes"
	cache="$pecan/.cache"
}

save(){
	if [[ -z "$name" ]] ; then
		name="$(cat $cache)"
		echo "no name supplied, using name $name"
	fi
	if [ ! -d "$themes/$name" ]; then
		mkdir "$themes/$name"
	fi
	cp "$pecan/style.css" "$themes/$name/style.css" &&
	cp "$pecan/scss/style.scss" "$themes/$name/style.scss" &&
	status="saved"
	screencapture "$themes/$name/$name.jpg"
	if command -v convert >/dev/null 2>&1; then
		convert "$themes/$name/$name.jpg" -geometry 1000 -quality 90 "$themes/$name/$name.jpg"
	touch "$themes/$name/README.md"
	echo "![$name]($name.jpg)" > "$themes/$name/README.md"
	echo "pecan style $name $status"
	fi
}

load(){
	status="loaded"
	if [[ -z "$name" ]] ; then
		dir="$themes"
		n_files="$(/bin/ls -1 "$dir" | wc -l | cut -f1)"
		rand_num="$(awk "BEGIN{srand();print int($n_files * rand()) + 1;}")"
		name="$(/bin/ls -1 "$dir" | sed -ne "${rand_num}p")"
	fi
	cp "$themes/$name/style.css" "$pecan/style.css" &&
	cp "$themes/$name/style.scss" "$pecan/scss/style.scss" &&
	echo "$name" > "$cache"
}

preview(){
	if [[ -z "$name" ]] ; then
		name="$(cat $cache)"
	fi
	echo "opening $name.jpg"
	feh "$themes/$name/$name.jpg"
}

list(){
	echo "available themes:"
	ls "$themes"
	echo "screenshots of themes are located in:"
	echo "$pecan/themes/"
}

notify(){
	if command -v notify-send >/dev/null 2>&1; then
		notify-send "pecan style $name $status"
	else
		echo "pecan style $name $status"
	fi
}

refresh(){
	# check if ubersicht is running
	ps cax | grep sicht > /dev/null
	if [ $? -eq 0 ]; then
		# stupid umlaut character
		ubersicht="$(ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut -d. -f1)"
		if [[ "$ubersicht" = "UM-LM^Hbersicht" ]] ; then
			ubersicht="Übersicht"
		fi
	#osascript -e 'tell application "'$ubersicht'" to refresh widget id "pecan-background-jsx"'
	osascript -e 'tell application "'$ubersicht'" to refresh'
	else
		echo "Ubersicht is not running."
	fi
}

getname() {
	echo "$(cat $cache)"
}

help(){
	echo "available flags:"
	echo "list themes: -ls or --list"
	echo "preview theme with feh: -p or --preview (theme name)"
	echo "load theme: -l or --load (theme name)"
	echo "(if no argument is provided, then a random theme will be chosen)"
	echo "save theme: -s or --save (theme name)"
	echo "(if no argument is provided, then then the most recently loaded will be chosen)"
	echo "echo current theme: -v"
	echo "help: -h or --help"
	echo "screenshots of themes are located in:"
	echo "$pecan/themes/"
}

case $1 in
	-p|--preview)
		setup
		preview
	;;
	-l|--load)
		setup
		load
		refresh
		notify
	;;
	-s|--save)
		setup
		save
		notify
	;;
	-v)
		setup
		getname
	;;
	-h|--help)
		help
		exit
	;;
	-ls|--list)
		setup
		list
	;;
	*)
		help
		exit
	;;
esac
