#!/usr/bin/env bash
#
# author: daniel neemann (@zzzeyez)
#
# requires Übersicht
# optional dependency: `imagemagick` (to save screenshots when saving theme)



#########################################
# change the variable below to point to #
# wherever your Übersicht widgets are.  #
#########################################
uber="$HOME/Library/Application Support/Übersicht/widgets"



name="$2"
themes="$uber/pecan/themes"
cache="${HOME}/.cache"

checkdir() {
if [ ! -d "$uber/pecan" ]; then
	echo "directory $uber/pecan not found"
	echo "please edit line 14 to include location of Übersicht widgets"
	echo "now exiting.."
	exit
fi
}

save(){
	if [[ -z "$name" ]] ; then
		name="$(cat $cache/pecan)"
		echo "no name supplied, using name $name"
	fi
	if [ ! -d "$themes/$name" ]; then
		mkdir "$themes/$name"
	fi
	cp "$uber/pecan/style.css" "$themes/$name/style.css" &&
	cp "$uber/pecan/scss/style.scss" "$themes/$name/style.scss" &&
	status="saved"
	screencapture "$themes/$name/$name.jpg"
	if command -v convert >/dev/null 2>&1; then
		convert "$themes/$name/$name.jpg" -geometry 1000 -quality 90 "$themes/$name/$name.jpg"
	touch "$themes/$name/README.md"
	echo "![$name]($name.jpg)" > "$themes/$name/README.md"
	echo "pecan style $name $status"
	fi
}

load(){
	if [[ -z "$name" ]] ; then
		dir="$themes"
		n_files="$(/bin/ls -1 "$dir" | wc -l | cut -f1)"
		rand_num="$(awk "BEGIN{srand();print int($n_files * rand()) + 1;}")"
		name="$(/bin/ls -1 "$dir" | sed -ne "${rand_num}p")"
	fi
	cp "$themes/$name/style.css" "$uber/pecan/style.css" &&
	cp "$themes/$name/style.scss" "$uber/pecan/scss/style.scss" &&
	status="loaded" & echo "$name" > "$cache/pecan"
}

preview(){
	feh "$themes/$name/$name.jpg"
}

list(){
	echo "available themes:"
	ls "$themes"
	echo "screenshots of themes are located in:"
	echo "$uber/pecan/themes/"
}

notify(){
	if command -v notify-send >/dev/null 2>&1; then
		notify-send "✔ pecan style $name $status"
	else
		echo "pecan style $name $status"
	fi
}

refresh(){
	# stupid umlaut character
	# osascript -e 'tell application "'$(ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut -d. -f1)'" to refresh'
	osascript -e 'tell application "Übersicht" to refresh widget id "pecan-background-coffee"'
}

help(){
	echo "available flags:"
	echo "list themes: -ls or --list"
	echo "preview theme with feh: -p or --preview (theme name)"
	echo "load theme: -l or --load (theme name)"
	echo "(if no argument is provided, then a random theme will be chosen)"
	echo "save theme: -s or --save (theme name)"
	echo "(if no argument is provided, then then the most recently loaded will be chosen)"
	echo "help: -h or --help"
	echo "screenshots of themes are located in:"
	echo "$uber/pecan/themes/"
}

checkdir
case $1 in
	-p|--preview)
		preview
	;;
	-l|--load) 
		load
		refresh
		#notify
	;;
	-s|--save)
		save
		exit
	;;
	-h|--help)
		help
	;;
	-ls|--list)
		list
	;;
	*)
		help
	;;
esac
