#!/usr/bin/env bash

sassc --style expanded "$(dirname "$0")/scss/style.scss" > "$(dirname "$0")/style.css" &&
osascript -e 'tell application "'$(ps ax | grep sicht | awk '{print $5}' | head -1 | cut -d/ -f3 | cut -d. -f1)'" to refresh widget id "Pecan-background-coffee"'
