#!/usr/bin/env bash
sed -i '' "s/zzzeyez/$USER/g" "$(dirname "$0")/scss/style.scss"
sassc --style expanded "$(dirname "$0")/scss/style.scss" > "$(dirname "$0")/style.css" &
ps cax | grep bersicht > /dev/null
if [ $? -eq 0 ]; then
	osascript -e 'tell application "Übersicht" to refresh widget id "pecan-background-coffee"'
fi
