#!/usr/bin/env bash

exists () {
    type "$1" &> /dev/null ;
}

if exists /usr/local/bin/ifstat ; then
	echo "↓ $(bash $(dirname "$0")/down) ↑ $(bash $(dirname "$0")/up)"
else
	echo "↓ $(networksetup -getairportnetwork en0 | cut -c 24-)"
fi

