#!/usr/bin/env bash

exists () {
    type "$1" &> /dev/null ;
}

if exists /usr/local/bin/ifstat ; then
    echo "$(/usr/local/bin/ifstat -n -z -S -i en0 1 1)"
else
	echo "↓ $(networksetup -getairportnetwork en0 | cut -c 24-)"
fi

